# Generated by Django 5.2.11 on 2026-02-11 23:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Número único do pedido (gerado automaticamente)",
                        max_length=20,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("em_processamento", "Em Processamento"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "chave_idempotencia",
                    models.CharField(
                        db_index=True,
                        help_text="Chave única para evitar pedidos duplicados",
                        max_length=255,
                        unique=True,
                        verbose_name="Chave de Idempotência",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço do produto no momento da compra",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preço Unitário",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
                "db_table": "itens_pedido",
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatusPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("em_processamento", "Em Processamento"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Status Anterior",
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("em_processamento", "Em Processamento"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        max_length=20,
                        verbose_name="Status Novo",
                    ),
                ),
                (
                    "alterado_por",
                    models.CharField(
                        blank=True,
                        help_text="Usuário ou sistema que realizou a alteração",
                        max_length=255,
                        null=True,
                        verbose_name="Alterado Por",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Data da Alteração",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Status",
                "verbose_name_plural": "Históricos de Status",
                "db_table": "historico_status_pedido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["cliente", "status"], name="idx_pedido_cliente_status"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["status", "created_at"], name="idx_pedido_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(fields=["numero"], name="idx_pedido_numero"),
        ),
        migrations.AddConstraint(
            model_name="pedido",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_total__gte", Decimal("0.00"))),
                name="pedido_valor_total_positivo",
            ),
        ),
        migrations.AddIndex(
            model_name="itempedido",
            index=models.Index(
                fields=["pedido", "produto"], name="idx_item_pedido_produto"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.UniqueConstraint(
                fields=("pedido", "produto"), name="unique_item_pedido_produto"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gte", 1)),
                name="item_quantidade_minima",
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.01"))),
                name="item_subtotal_positivo",
            ),
        ),
        migrations.AddIndex(
            model_name="historicostatuspedido",
            index=models.Index(
                fields=["pedido", "created_at"], name="idx_historico_pedido_data"
            ),
        ),
    ]
