# Generated by Django 5.2.11 on 2026-02-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="numero",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Número único do pedido (gerado automaticamente)",
                max_length=30,
                unique=True,
                verbose_name="Número",
            ),
        ),
    ]
