# Generated by Django 5.2.11 on 2026-02-11 23:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Código único do produto (Stock Keeping Unit)",
                        max_length=50,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nome"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço unitário do produto",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preço",
                    ),
                ),
                (
                    "quantidade_estoque",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produtos",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        fields=["nome", "ativo"], name="idx_produto_nome_ativo"
                    ),
                    models.Index(fields=["sku", "ativo"], name="idx_produto_sku_ativo"),
                    models.Index(
                        fields=["ativo", "quantidade_estoque"],
                        name="idx_produto_ativo_estoque",
                    ),
                ],
            },
        ),
    ]
