# Generated by Django 5.2.11 on 2026-02-11 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nome"
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        db_index=True,
                        help_text="CPF (11 dígitos) ou CNPJ (14 dígitos)",
                        max_length=18,
                        unique=True,
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, null=True, verbose_name="Endereço"),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["nome", "ativo"], name="idx_cliente_nome_ativo"
                    ),
                    models.Index(
                        fields=["email", "ativo"], name="idx_cliente_email_ativo"
                    ),
                ],
            },
        ),
    ]
